[package]
name = "pico-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pico-blink"
path = "src/main.rs"

[dependencies]
pico-hal-adapter = { path = "../hal-adapter" }
pico-core = { path = "../core" }
cortex-m-rt = { workspace = true }
cortex-m = { workspace = true }
defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
heapless = { workspace = true }
embedded-hal = { workspace = true }
